[package]
name = "darkpage-website"
version = "0.0.1"
license = "GPL-3"
edition = "2021"

[dependencies]
axum = "0.6.20"
tokio = { version = "1", features = ["full"] }
flurry  = "0.4.0"
once_cell = "1.18.0"
walkdir = "2"
toml = "0.8.2"